services:
  - type: web
    name: frape-club
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: NODE_ENV
        value: production
